services:
  - type: web
    name: cv-generator
    env: docker
    plan: free
    dockerCommand: gunicorn --bind 0.0.0.0:8000 --timeout 120 --workers 1 --threads 2 app:app
    healthCheckPath: /
    envVars:
      # Empêche Playwright de planter par manque de mémoire dans le mode headless
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
